-- MySQL Script generated by MySQL Workbench
-- Tue Apr  6 19:10:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema forum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema forum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `forum` DEFAULT CHARACTER SET utf8 ;
USE `forum` ;

-- -----------------------------------------------------
-- Table `forum`.`registration_form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`registration_form` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `e-mail` VARCHAR(254) NOT NULL,
  `nickname` VARCHAR(15) NOT NULL,
  `password_hash` CHAR(64) NOT NULL,
  `time` BIGINT(20) NOT NULL,
  `confirm_hash` CHAR(64) NOT NULL,
  `is_complete` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forum`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `e-mail` VARCHAR(254) NOT NULL,
  `nickname` VARCHAR(15) NOT NULL,
  `password_hash` CHAR(64) NOT NULL,
  `is_admin` TINYINT NOT NULL,
  `registration_date` DATE NOT NULL,
  `last_activity` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `e-mail_UNIQUE` (`e-mail` ASC) VISIBLE,
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forum`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`session` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `hash` CHAR(64) NOT NULL,
  `time` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_session_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_session_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `forum`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forum`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`section` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forum`.`theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`theme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(75) NOT NULL,
  `user_id` INT NOT NULL,
  `section_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `section_id`),
  INDEX `fk_theme_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_theme_section1_idx` (`section_id` ASC) VISIBLE,
  CONSTRAINT `fk_theme_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `forum`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_theme_section1`
    FOREIGN KEY (`section_id`)
    REFERENCES `forum`.`section` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forum`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT(500) NOT NULL,
  `is_edit` TINYINT NOT NULL,
  `last_edit` DATETIME NULL,
  `user_id` INT NOT NULL,
  `theme_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `theme_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_post_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_post_theme1_idx` (`theme_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `forum`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_theme1`
    FOREIGN KEY (`theme_id`)
    REFERENCES `forum`.`theme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forum`.`mailbox`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`mailbox` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `to_user` INT NOT NULL,
  `from_user` INT NOT NULL,
  `text` TEXT(500) NOT NULL,
  `datetime` DATETIME NOT NULL,
  `is_read` TINYINT NOT NULL,
  PRIMARY KEY (`id`, `to_user`, `from_user`),
  INDEX `fk_mailbox_user1_idx` (`to_user` ASC) VISIBLE,
  INDEX `fk_mailbox_user2_idx` (`from_user` ASC) VISIBLE,
  CONSTRAINT `fk_mailbox_user1`
    FOREIGN KEY (`to_user`)
    REFERENCES `forum`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mailbox_user2`
    FOREIGN KEY (`from_user`)
    REFERENCES `forum`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
